
GET http://localhost:5000/posts
###
GET http://localhost:5000/posts/5e839012a2b92c293c42053f
###
DELETE http://localhost:5000/posts/5eb8575257d9fd1c746a4630
###
PATCH  http://localhost:5000/posts/5eb88daae0a5da20fc3cb61a HTTP/1.1
content-type: application/json

{
    "Name": "ESP_fake2",
    "Place": "Generic fake",
    "Ip": "http://192.168.1.30/body",
    "Description": "Feliz por siempre",
    "State": false
}
###
PATCH  http://localhost:5000/posts/5eb88daae0a5da20fc3cb61a HTTP/1.1
content-type: application/json

{
    "State": false
}

###
POST http://localhost:5000/posts HTTP/1.1
content-type: application/json

{
    "Name": "ESP_fake2",
    "Place": "Generic",
    "Ip" : "http://192.168.1.30/body",
    "Description": "Jodido por siempre",
    "State":false
}

###
POST http://192.168.1.17:8080/playmp3.php?playaudio=ding.mp3
###
POST  http://192.168.1.32/body HTTP/1.1
content-type: application/json

{   
    "State" : true    
}
###
POST http://192.168.1.19:8080/body?led=0
###
POST http://192.168.1.19:8080/body?led=1
###
POST  http://192.168.1.30/body HTTP/1.1
content-type: application/json

{   
    "State" : true    
}
