
GET http://localhost:3000/posts
###
GET http://localhost:3000/posts/5e839012a2b92c293c42053f
###
DELETE http://localhost:3000/posts/5ea71bd2b359df3d4451d49c
###
PATCH  http://localhost:3000/posts/5ea6fe110524da3f2855ad5f HTTP/1.1
content-type: application/json

{
    "State": false
}
###
PATCH  http://localhost:3000/posts/5ea6fe110524da3f2855ad5f HTTP/1.1
content-type: application/json

{
    "State": true
}

###
POST http://localhost:3000/posts HTTP/1.1
content-type: application/json

{
    "Name": "deleteme",
    "Ip" : "http://192.168.1.30/body",
    "Description": "GENERIC ESP8266 MODULE (ESP8266-01). Use Library esp8266 by esp8266 community V.2.5.0",
    "State":true
}

###
POST http://192.168.1.17:8080/playmp3.php?playaudio=ding.mp3
###
POST  http://192.168.1.32/body HTTP/1.1
content-type: application/json

{   
    "State" : true    
}
###
POST http://192.168.1.19:8080/body?led=0
###
POST http://192.168.1.19:8080/body?led=1
###
POST  http://192.168.1.30/body HTTP/1.1
content-type: application/json

{   
    "State" : true    
}
